import { useEffect } from "react";
import Modal from "../../components/coffeeModal";
import useToggleModal from "../../hooks/useModal";

export default function Privacy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const { modal, toggleModal } = useToggleModal();
  return (
    <div className="xs:text-md xs:p-5 flex flex-col overflow-hidden bg-white font-text text-navbar md:px-[15%] md:py-[10%] md:text-lg">
      <Modal toggleModal={toggleModal} modal={modal} />
      <Section
        title="Privacy Policy"
        className="xs:text-[45px] mb-[80px] font-normal uppercase md:text-[60px]"
      >
        <p className="italic">Effective date: 26 December 2019</p>
        <br />
        <p>Animista collects some Personal Data from its Users.</p>
      </Section>

      <Section title="TL;DR Version" className="">
        <SubSection title="Analytics" className="">
          <span className="mb-0 font-bold">Google Analytics</span>
          <br />
          <p>Personal Data: Cookies; Usage Data</p>
        </SubSection>
        <SubSection title="Advertising" className="">
          <span className="mb-0 font-bold">BuySellAds</span>
          <br />
          <p>Personal Data collected: Cookies and Usage Data.</p>
        </SubSection>
        <SubSection title="Managing contacts and sending messages" className="">
          <span className="mb-0 font-bold">Mailchimp</span>
          <br />
          <p>Personal Data: email address</p>
        </SubSection>
      </Section>

      <Section title="COMPLETE PRIVACY POLICY" className="">
        <p>
          Animista ("us", "we", or "our") operates the animista.net website
          (hereinafter referred to as the "Service").
        </p>
        <br />
        <p>
          This page informs you of our policies regarding the collection, use,
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
        </p>
        <br />
        <p>
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy.
        </p>
      </Section>

      <Section title="Definitions" className="">
        <SubSection title="Service" className="">
          <p>Service is the animista.net website/application.</p>
          <br />
        </SubSection>
        <SubSection title="Personal Data" className="">
          <p>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
          <br />
        </SubSection>
        <SubSection title="Usage Data" className="">
          <p>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>
          <br />
        </SubSection>
        <SubSection title="Cookies" className="">
          <p>
            Cookies are small files stored on your device (computer or mobile
            device).
          </p>
        </SubSection>
      </Section>

      <Section title="Information Collection and Use" className="">
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you:
        </p>
        <br />
        <SubSection title="Personal Data" className="">
          <p>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you ("Personal Data"). Personally identifiable information
            may include, but is not limited to:
          </p>
          <br />
          <ul className="xs:text-sm flex translate-x-[10%] list-disc flex-col gap-y-3 md:text-base">
            <li>Email address</li>
            <li>Cookies</li>
            <li>Usage Data</li>
          </ul>
        </SubSection>
        <SubSection title="Usage Data" className="">
          <p>
            We may also collect information how the Service is accessed and used
            ("Usage Data"). This Usage Data may include information such as your
            computer's Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data.
          </p>
          <br />
        </SubSection>
        <SubSection title="Tracking and Cookies Data" className="">
          <p>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <br />
          <p>
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyse our Service.
          </p>
          <br />
          <p>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
        </SubSection>
      </Section>

      <Section title="Use of Data" className="">
        <p>Animista uses the collected data for various purposes:</p>
        <br />
        <ul className="xs:text-sm flex translate-x-[10%] list-disc flex-col gap-y-3 md:text-base">
          <li>To provide and maintain the Service</li>
          <li>To notify you about changes to our Service</li>
          <li>
            To allow you to participate in interactive features of our Service
            when you choose to do so
          </li>
          <li>To provide customer care and support</li>
          <li>
            To provide analysis or valuable information so that we can improve
            the Service
          </li>
          <li>To monitor the usage of the Service</li>
          <li>To detect, prevent and address technical issues</li>
        </ul>
      </Section>

      <Section title="Transfer Of Data" className="">
        <p>
          Your information, including Personal Data, may be transferred to and
          maintained on computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ than those from your jurisdiction.
        </p>
        <br />
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <br />
        <p>
          Animista will take all steps reasonably necessary to ensure that your
          data is treated securely and in accordance with this Privacy Policy
          and no transfer of your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
      </Section>

      <Section title="Disclosure Of Data" className="">
        <p>
          Animista may disclose your Personal Data in the good faith belief that
          such action is necessary to:
        </p>
        <br />
        <ul className="xs:text-sm flex translate-x-[10%] list-disc flex-col gap-y-3 md:text-base">
          <li>To comply with a legal obligation</li>
          <li>To protect and defend the rights or property of Animista</li>
          <li>
            To prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            To protect the personal safety of users of the Service or the public
          </li>
          <li>To protect against legal liability</li>
        </ul>
        <br />
        <p>
          As an European citizen, under GDPR, you have certain individual
          rights. You can learn more about these guides in the{" "}
          <a
            target="_blank"
            href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR"
            className="text-lightred hover:underline"
          >
            GDPR Guide
          </a>
          .
        </p>
      </Section>

      <Section title="Security of Data" className="">
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
      </Section>

      <Section title="Service Providers" className="">
        <p>
          We may employ third party companies and individuals to facilitate our
          Service ("Service Providers"), to provide the Service on our behalf,
          to perform Service-related services or to assist us in analyzing how
          our Service is used.
        </p>
        <br />
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>

        <SubSection title="Analytics" className="">
          <p>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
          <br />
          <span className="font-bold">Google Analytics (Google LLC)</span>
          <br />
          <br />
          <p>
            Google Analytics is a web analysis service provided by Google LLC
            (“Google”). Google utilizes the Data collected to track and examine
            the use of Animista, to prepare reports on its activities and share
            them with other Google services.
          </p>
          <br />
          <p>
            Google may use the Data collected to contextualize and personalize
            the ads of its own advertising network.
          </p>
          <br />
          <p>Personal Data collected: Cookies; Usage Data.</p>
          <br />
          <p>
            Place of processing: United States –{" "}
            <a
              target="_blank"
              href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR"
              className="text-lightred hover:underline"
            >
              Privacy Policy
            </a>{" "}
            –{" "}
            <a
              target="_blank"
              href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR"
              className="text-lightred hover:underline"
            >
              Opt Out
            </a>
            . Privacy Shield participant.
          </p>
        </SubSection>
        <SubSection title="Advertising" className="">
          <p>
            This type of service allows User Data to be utilized for advertising
            communication purposes displayed in the form of banners and other
            advertisements on this Website, possibly based on User interests.
          </p>
          <br />
          <p>
            This does not mean that all Personal Data are used for this purpose.
            Information and conditions of use are shown below. Some of the
            services listed below may use Cookies to identify Users or they may
            use the behavioral retargeting technique, i.e. displaying ads
            tailored to the User’s interests and behavior, including those
            detected outside this Website. For more information, please check
            the privacy policies of the relevant services.
          </p>
          <br />
          <p>
            In addition to any opt-out offered by any of the services below, the
            User may opt out of a third-party service's use of cookies by
            visiting the Network Advertising Initiative opt-out page.
          </p>
          <br />
          <span className="font-bold">BuySellAds (BuySellAds.com Inc.)</span>
          <br />
          <br />
          <p>
            BuySellAds is an advertising service provided by BuySellAds.com Inc.
          </p>
          <br />
          <p>Personal Data collected: Cookies and Usage Data.</p>
          <br />
          <p>
            Place of processing: United States –{" "}
            <a
              target="_blank"
              href="https://buysellads.com/about/privacy"
              className="text-lightred hover:underline"
            >
              Privacy Policy
            </a>
            .
          </p>
        </SubSection>
        <SubSection title="Managing contacts and sending messages" className="">
          <p>
            This type of service makes it possible to manage a database of email
            contacts, phone contacts or any other contact information to
            communicate with the User
          </p>
          <br />
          <p>
            These services may also collect data concerning the date and time
            when the message was viewed by the User, as well as when the User
            interacted with it, such as by clicking on as included in the
            message.
          </p>
          <br />
          <span className="font-bold">
            Mailchimp (The Rocket Science Group LLC)
          </span>
          <br />
          <br />
          <p>
            Mailchimp is an email address management and message sending service
            provided by The Rocket Science Group LLC.
          </p>
          <br />
          <p>Personal Data collected: email address.</p>
          <br />
          <p>
            Place of processing: United States –{" "}
            <a
              target="_blank"
              href="https://mailchimp.com/legal/privacy/"
              className="text-lightred hover:underline"
            >
              Privacy Policy
            </a>{" "}
            . Privacy Shield participant.
          </p>
        </SubSection>
      </Section>

      <Section title="Links to Other Sites" className="">
        <p>
          Our Service may contain as to other sites that are not operated by us.
          If you click a third party a, you will be directed to that third
          party's site. We strongly advise you to review the Privacy Policy of
          every site you visit.
        </p>
        <br />
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
      </Section>

      <Section title="Children's Privacy" className="">
        <p>
          Our Service does not address anyone under the age of 18 ("Children").
        </p>
        <br />
        <p>
          We do not knowingly collect personally identifiable information from
          anyone under the age of 18. If you are a parent or guardian and you
          are aware that your Child has provided us with Personal Data, please
          contact us. If we become aware that we have collected Personal Data
          from children without verification of parental consent, we take steps
          to remove that information from our servers.
        </p>
      </Section>

      <Section title="Changes to This Privacy Policy" className="">
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <br />
        <p>
          You are advised to review this Privacy Policy periodically for any
          mb-0 changes. Changes to this Privacy Policy are effective when they
          are posted on this page.
        </p>
      </Section>

      <Section title="Contact Us" className="">
        <p>
          If you have any questions about this Privacy Policy, please contact us
          by email: cssanimista@gmail.com
        </p>
      </Section>
    </div>
  );
}

interface SectionProps {
  title: string;
  children: React.ReactNode;
  className: string;
}

function Section({ title, children, className }: SectionProps) {
  return (
    <div className="mt-8">
      <h2
        className={`${className} xs:text-[20px] my-[35px] font-normal md:text-[30px]`}
      >
        {title}
      </h2>
      {children}
    </div>
  );
}

function SubSection({ title, children, className }: SectionProps) {
  return (
    <div className="my-10">
      <h3
        className={`${className} xs:text-[15px] my-5 font-normal md:text-[25px]`}
      >
        {title}
      </h3>
      {children}
    </div>
  );
}
